### ISSUE TITLE
deleting node via predicate should only delete edge

### ISSUE THREAD

**Issue by haseebrabbani** [xanthous-tech/dgraph-orm#31]
after calling `IPredicate.delete(node: T)`, the generated mutation also removes all node data and edges as seen here: https://github.com/xanthous-tech/dgraph-orm/blob/83a9d1e054a65bf29285ef38dec2b2dfb15923d4/src/transaction/mutation-builder.ts#L119

this should be optional: there should be a way to configure whether you want just the predicate edge deleted or the entire node as well.

**Comment by lhr0909** [comment]
Fixed in #34
