### ISSUE TITLE
Falsey facet values ignored by transaction builder

### ISSUE THREAD

**Issue by andrejpavlovic** [xanthous-tech/dgraph-orm#40]
This line of code here should be checking if the value is `undefined` rather than falsey. It's causing facets with `0` value to be ignored by the transaction builder.

https://github.com/xanthous-tech/dgraph-orm/blob/80a1e457a5854595908fcbe5a95f6b3b43a365c2/src/transaction/transaction.ts#L264-L266

Created pull request to complement this issue report: https://github.com/xanthous-tech/dgraph-orm/pull/39

**Comment by lhr0909** [comment]
resolved by #39
